# Generated by Django 3.2.18 on 2023-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titbit', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
